### ISSUE TITLE
Connecting to Self signed HTTPS server

### ISSUE THREAD

**Issue by szandras2524** [synhershko/NAppUpdate#69]
Hi,

i found your "product" great stuff! Is it possible to connect via an self signed cert to https server? 

Thanks a lot !

András Székely
Hungary

**Comment by robinwassen** [comment]
Hi @szandras2524,

If you use SimpleWebSource as update source it just uses System.Net.WebRequest for the connection to fetch the feed and files.

It is possible to accept self signed certs globally that covers WebRequest, more in detail here: http://stackoverflow.com/questions/12506575/how-to-ignore-the-certificate-check-when-ssl

Otherwise there are no built-in support for accepting self signed certs in NAppUpdate, and I hope you know what you are doing when you go down the route of accepting any cert.

Regards,
Robin

**Comment by szandras2524** [comment]
THANKS A LOT FOR YOUR ANSWER !

Have a nice happy day !

András
